wandb_version: 1

learning_rate:
  desc: null
  value: 0.002
ent:
  desc: null
  value: 0.0001
layer size:
  desc: null
  value: 256
gamma:
  desc: null
  value: 0.99
lambda:
  desc: null
  value: 0.98
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712624159.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
